name: test
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./website/yarn.lock
      - name: Install dependencies
        working-directory: website
        run: yarn
      - name: Test build website
        working-directory: website
        run: yarn build
